### ISSUE TITLE
Feature request: allow switching to repl

### ISSUE THREAD

**Issue by chpatrick** [ndmitchell/ghcid#303] opened 2020-02-26 08:14 UTC
When working on a big Haskell project it can be a bit painful to run ghcid as well as another ghci instance for using the REPL. It would be fantastic if it would be possible to switch back and forth between "ghcid mode" and regular ghcid for the same session (like Ctrl-O in `mc`).

**Comment by moodmosaic** [comment] 2020-02-26 10:04
I'd be surprised if this can be efficiently done for all supported operating systems. It'd be an awesome feature, however.

**Comment by ndmitchell** [comment] 2020-02-26 21:15
Closing as a dupe of https://github.com/ndmitchell/ghcid/issues/250 - unfortunately it's a rather hard thing to do!

**Closed** 2020-04-12 21:20 UTC
