### ISSUE TITLE
stack integration

### ISSUE THREAD

**Issue by mitchellwrosen** [ndmitchell/ghcid#38] opened 2015-06-11 06:47 UTC
`stack` unfortunately (or fortunately) is yet another tool projects can be built with. I believe it deprecates cabal sandboxes and cabal install entirely. A stack-based project can jump into a ghci session with `stack ghci`.

**Comment by mitchellwrosen** [comment] 2015-06-11 06:57
Ah, I'm an idiot, you can already specify the command with `--command`. Still, it would be convenient to default to `stack ghci` if `stack.yaml` exists.

**Comment by ndmitchell** [comment] 2015-06-11 08:19
I am a big fan of `stack` :). You would need a newish Stack (last 2 days), since https://github.com/commercialhaskell/stack/issues/130 was fixed after the first release.

**Comment by ndmitchell** [comment] 2015-06-11 08:40
Actually, that issue isn't yet closed, so you can't have `stack` integration yet - but as soon as the issue is fixed I'll integrate it.

**Comment by afcowie** [comment] 2015-06-15 23:30
I just did:

```shell
$ ghcid --command="stack exec ghci tests/Snippet.hs"
```

and things worked. That remains insanely difficult to form correctly, but it's how I'm running **ghcid** against individual programs in a project (that lack their own _.cabal_ stanzas) [This is returning to the discussion in #23 about default actions. I keep thinking that:

```
$ stack exec ghcid FileName.hs
```

could work, but my mental model of what's going on appears to be off.

AfC

**Comment by mitchellwrosen** [comment] 2015-06-15 23:39
`stack exec ghcid FileName.hs` will run `ghcid FileName.hs` with the proper package databases, etc, but that's not how you run ghcid on a file.

**Comment by ndmitchell** [comment] 2015-06-16 17:21
But it could be! @mitchellwrosen and @afcowie, I have a set of inputs and I need to transform them into a command line:

* Booleans for each of whether there is a `.cabal`, `stack.yaml` or `.ghci` file in the current directory.
* A list of command line arguments (e.g. `ghcid FileName.hs` would give `FileName.hs`).

What command line should I produce? When you say `stack exec ghcid FileName.hs` runs with the "proper" package databases, does that mean that `ghci FileName.hs` will then work to load everything up?

**Comment by mitchellwrosen** [comment] 2015-06-16 20:01
Hmm... yeah, it's a bit confusing... is this how it works currently?

- If `.ghci` then `ghci` (only useful if your `.ghci` loads a module)
- If `.cabal` then `cabal repl`
- If `stack.yaml` then `stack ghci`

I think `stack exec ghcid Foo.hs` would work if `ghcid` could "know" that it was being executed by `stack`, and not the shell, in which case it should, in turn, spawn `ghci Foo.hs`. `stack exec ghcid Foo.hs` might simply be the wrong way to use ghcid+stack, for that reason.

**Comment by ndmitchell** [comment] 2015-06-16 20:45
Yep, you have the current mechanism right. I want to add arguments as well, which will change things (e.g. I might run `cabal ghci args` if I have args instead of `cabal repl`). I think `ghcid` should probably know about `stack`, but `stack` shouldn't know about `ghcid`, so I doubt `stack exec ghcid` will ever work, but `ghcid` might call `stack exec` itself.

**Comment by afcowie** [comment] 2015-06-18 01:13
@ndmitchell so as far as I can tell, all _cabal exec_ / _stack exec_ are doing is setting up the `GHC_PACKAGE_PATH` environment variable so that subsequent _ghc_ / _ghci_ commands work with the local sandbox.

So given **ghcid** is just a wrapper around running _ghc_ is the reason that my convoluted `ghcid --command="cabal exec ghci tests/Snippet.hs"` has worked.

@mitchellwrosen the whole point is just to be able to run ghcid against a specific _.hs_ file, rather than relying on having an entire cabal stanza just for quickly testing a fragment.

AfC

**Comment by ndmitchell** [comment] 2015-06-19 11:21
The stack behaviour changed, and keeps changing, so I'll wait until they finish doing things before supporting it natively: https://github.com/commercialhaskell/stack/issues/355

**Comment by ndmitchell** [comment] 2015-06-19 21:15
The "what command line should we run" was tracked at #23, and I've updated that and closed it, so I'll leave this just for the stack integration.

**Comment by afcowie** [comment] 2015-07-03 04:57
Argh. What I was doing isn't working anymore. As far as I can make out, `stack ghci` isn't actually doing `stack build` and meanwhile `stack ghci tests/Experiment.hs` isn't loading anything. Just when I was starting to be productive again. :(

**Comment by afcowie** [comment] 2015-07-03 05:31
(forget the comment I just made; I forgot that in other projects I had a _.ghci_ that specified:

```
:set -ilib:src:tests
```
and with that `stack exec ghcid tests/Experiment.hs` is working [again]. I look forward to you getting the feature(s) you need stable in **stack** and invoking it [more] intelligently)

**Comment by ndmitchell** [comment] 2015-09-28 09:39
I gave it another bash. Unfortunately https://github.com/commercialhaskell/stack/issues/1067 means Stack can't open ghcid in ghci, so it's not really ready for prime time.

**Comment by ndmitchell** [comment] 2015-09-28 09:42
(In the process, I raised 7 separate Stack tickets!)

**Comment by ndmitchell** [comment] 2016-01-05 11:58
I raised a ticket to make Stack and ghcid play nicely on their tracker: https://github.com/commercialhaskell/stack/issues/1608

**Comment by ChristopherKing42** [comment] 2016-03-02 22:45
@ndmitchell Any other stack issues keeping this open?

**Comment by ndmitchell** [comment] 2016-03-03 10:52
@ChristopherKing42 - not really sure where the Stack bugs are or aren't... To be useful, ghcid really needs a command to run that uses stack and opens up into a prompt. Doing a survey of some of my projects, both with their .ghci file and without:

* Hoogle, works with and without .ghci.
* Shake, a total basket case, "module `main@main:Run' is defined in multiple files"
* Ghcid, loads up the executable, but not the test suite.
* Extra, loads up the executable, but not the test suite.

If I pass `--no-load` to Ghcid or Extra then it fails because I don't have QuickCheck already installed in my sandbox. I've raised https://github.com/commercialhaskell/stack/issues/1871 to ask for a flag, and then I'd probably do the logic:

* If you have a `.stack.yml` and `.ghci` and `.stack-work` I run `stack ghci --no-load`.
* If you have a `.stack.yml` and no `.ghci` and `.stack-work` I run `stack ghci`.

The idea of checking for `.stack-work` is so that projects that have `.stack.yml` but who have users who chose to use something else don't get impacted.

**Comment by ndmitchell** [comment] 2016-03-03 11:23
So `--test` is the magic if the first case. With that, I think it's just a question of implementing those semantics.

**Comment by luigy** [comment] 2016-03-03 11:30
> Shake, a total basket case, "module `main@main:Run' is defined in multiple files"

interesting, what command did you run for this?
this loaded fine for me
a git clone + stack init + stack ghci --test --no-load

**Comment by luigy** [comment] 2016-03-03 11:40
Wait, I think I know.  This is probably without the `--no-load` and no targets.  That would be this issue https://github.com/commercialhaskell/stack/issues/1606 and is because stack it's not smart enough for your style of reusing Main modules across components :joy:  
( I did suggest refactoring as the lazy solution :see_no_evil: )  I'll probably give it a try sometime

**Comment by ndmitchell** [comment] 2016-03-03 12:32
With `--test --no-load` Shake works perfectly, so I think I'm now happy enough with it, no real desire to change either Shake or Ghcid.

**Comment by ChristopherKing42** [comment] 2016-03-03 17:15
@ndmitchell Should the readme be changed then?

**Comment by ndmitchell** [comment] 2016-03-03 17:49
> no real desire to change either Shake or Ghcid

To clarify, I have no desire to avoid `-main-is` in Ghcid, but I do now want to support Stack properly using the techniques and choices above.

@ChristopherKing42 - I'd much rather fix the code first, then update the readme to reflect all of that at once.

**Comment by ndmitchell** [comment] 2016-04-04 19:13
All implemented as described above, and seems to work nicely.

I intend to release a new version of Ghcid incorporating these changes in the next few days, so if anyone wants to try in advance, please do so.

**Closed** 2016-04-04 19:13 UTC
