### ISSUE TITLE
Multi-project stack does not properly reload

### ISSUE THREAD

**Issue by rvion** [ndmitchell/ghcid#57] opened 2016-04-12 07:43 UTC
@ndmitchell  I have a problem with ghcid 0.6.1

__It is currently impossible to start ghcid so it reloads my code when some *.hs file change in my multi-package project__

I use stack, I have a set of ~10 packages within one same folder.
All of them have a src folder containing module tree (Foo.hs, Foo/Bar.hs, etc.)
I have one empty package at the top level importing all other packages to simplify compatibility with cabal specific stuff (like haskell-ide-atom).

  - default doesn't work 

    `ghcid` --> never reload when any file changes

    (this is probably a bug 🐛  related to this message printed in ghci: )
    ```
    * * * * * * * *
    The main module to load is ambiguous. Candidates are:
    1. Package `app' component exe:app-example with main-is file: /Users/rvion/dev/cogito/app/Main.hs
    2. Package `pghs' component exe:pg2hs with main-is file: /Users/rvion/dev/cogito/pghs/Main.hs
    You can specify which one to pick by:
     * Specifying targets to stack ghci e.g. stack ghci app:exe:app-example
    Specify main module to use (press enter to load none): Not loading any main modules, as no valid     module selected
     * Specifying what the main is e.g. stack ghci --main-is app:exe:app-example
    
     * Choosing from the candidate above [1..2]
    * * * * * * * *
    ```

  - command to load top level package doesn't work because it doesn't watch local deps change

    `ghcid -c "stack ghci toplevelpackage"
  - one reload param with list of file doesn't watch

    `ghcid --test="testFunction" --reload="**/*.hs"` -> loop weirdly because of "**/*.hs"
  - one --reload per folder doesn't work because no recursivity 

    `ghcid --reload pkg1 --reload pkg2 ` --> never reload when pkg1/src/**/*.hs change because only watch for pkg1/* (direct folder, no recursive)

So far:  the only 2 solutions I thought about were
  1. make a giant cmd like
    ```shell
    ghcid ... \
       --reload pkg1/src/ \
       --reload pkg1/src/Foo \
       --reload pkg1/src/Foo/Bar \
    
       --reload pkg2/src/ \
      -- ...
    ```
    possible partial workaround: 
    ```shell 
    ghcid  $(ls **/*.hs | while read -r line; do dirname "$line"; done | uniq | sed 's/^/--reload=/' | tr '\n' ' ' | sed 's/ $//g')
    ```
  2. start one ghcid cmd per package

I went with (1) but then I found a bug 🐛  in ghcid: 
```
ghcid --reload=pkg1/src/
```
doens't reload anything unless I'm specifying a target.
since I have several executables, not specifying a target shows

```shell
* * * * * * * *
The main module to load is ambiguous. Candidates are:
1. Package `app' component exe:app-example with main-is file: /Users/rvion/dev/cogito/app/Main.hs
2. Package `pghs' component exe:pg2hs with main-is file: /Users/rvion/dev/cogito/pghs/Main.hs
You can specify which one to pick by:
 * Specifying targets to stack ghci e.g. stack ghci app:exe:app-example
Specify main module to use (press enter to load none): Not loading any main modules, as no valid module selected
 * Specifying what the main is e.g. stack ghci --main-is app:exe:app-example

 * Choosing from the candidate above [1..2]
* * * * * * * *
```

and then no reload occurs at all

so I did 
```shell
ghcid -c "stack ghci toplevelpackage" --reload=pkg1/src/ --reload=pkg1/src/Foo --reload=...
```
but arg again: ghci don't reload files in pkg1 since I specified `toplevelpackage`. so `toplevelpackage` reload when I change pkg1, but it doesn't pick changes in pkg1

Otherwise, great project ! Thanks

**Comment by rvion** [comment] 2016-04-12 08:36
after some more experimentation, I didn't find any way for me to reload default ghcid command when any **/*.hs change.

**Comment by ndmitchell** [comment] 2016-04-12 08:37
Reload can take a directory name or a file name. It can't take patterns and it doesn't deal with recursive directories. These are deliberate limitations - things that could be fixed, but generally needing super-powerful reloading is a good sign that something else is broken. In this case, clearly something else is broken! It should be all automatic.

When you run `ghcid` the first line should be something like:

    Loading stack ghci --test --no-load --ghci-options=-fno-code ...

What is the associated command? If you run the associated command (e.g. `stack ghci --test --no-load --ghci-options=-fno-code` in this case), what does Stack load? Do you have a `.ghci` file? If you do `:show modules` what does it say?

**Comment by rvion** [comment] 2016-04-12 08:40
`stack ghci --test --no-load --ghci-options=-fno-code `
doens't :show modules
```shell 
$ stack ghci --test --no-load --ghci-options=-fno-code
Configuring GHCi with the following packages: cogito, app, orm, pghs, types
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> :show modules
Prelude>
```

but...

```
$ ghcid
Loading stack ghci --test --ghci-options=-fno-code ...

* * * * * * * *
The main module to load is ambiguous. Candidates are:
1. Package `app' component exe:app-example with main-is file: /Users/rvion/dev/cogito/app/Main.hs
2. Package `pghs' component exe:pg2hs with main-is file: /Users/rvion/dev/cogito/pghs/Main.hs
You can specify which one to pick by:
Specify main module to use (press enter to load none): Not loading any main modules, as no valid module selected
 * Specifying targets to stack ghci e.g. stack ghci app:exe:app-example

 * Specifying what the main is e.g. stack ghci --main-is app:exe:app-example
 * Choosing from the candidate above [1..2]
* * * * * * * *

Configuring GHCi with the following packages: cogito, app, orm, pghs, types
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[ 1 of 40] Compiling PG.Types         ( /Users/rvion/dev/cogito/pghs/src/PG/Types.hs, nothing )
[ 2 of 40] Compiling PG.Dump          ( /Users/rvion/dev/cogito/pghs/src/PG/Dump.hs, nothing )
[ 3 of 40] Compiling Gen.Types        ( /Users/rvion/dev/cogito/pghs/src/Gen/Types.hs, nothing )
[ 4 of 40] Compiling Gen.Pluralize    ( /Users/rvion/dev/cogito/pghs/src/Gen/Pluralize.hs, nothing )
...
```

**Comment by ndmitchell** [comment] 2016-04-12 08:41
Do you have a `.ghci` file?

**Comment by rvion** [comment] 2016-04-12 08:41
No, I don't have a .ghci file (sorry, I was still writing the other part of my answer ^^)

**Comment by rvion** [comment] 2016-04-12 08:47
> Reload can take a directory name or a file name. It can't take patterns and it doesn't deal with recursive directories. These are deliberate limitations  
Completely makes sense to me

the strange thing (bug?) is that

`ghcid` doens't reload anything by default
`ghcid --reload="..."` __doens't reload anything either despite the param__

but 

`ghcid -c "stack ghci sometarget"` reload `sometarget`

and 

`ghcid -c "stack ghci sometarget" --reload="local-dep-1/src"` reload `sometarget` 
  - when any of its source files changed 
  - when local-dep-1/src/* change, 

but in both cases, __it doens't reload modules of local-dep-1__

**Comment by ndmitchell** [comment] 2016-04-12 15:38
Let's focus on the first problem first - why doesn't just plain vanilla `ghcid` work. It isn't loading anything to start with, so nothing else works. The entire problem seems to come back to the `--no-load` on the initial command line, and reading the logic:

    ["--no-load" | ".ghci" `elem` files] ++

What command do you use to start `ghcid`? Which directory are you starting `ghcid` from? Can you do a `ls -a` on that? Is there a `.ghci` file or directory?

**Comment by rvion** [comment] 2016-04-12 16:35
@ndmitchell 

I made this repo for you to reproduce easilly https://github.com/rvion/ghcid-bug-repro

if you clone it and run `ghcid`, you'll see that nothing reload when you change file.
If you specify one specifc project (`a`, `b`, or `ghcid-test`), then ghcid will only reload modules from that project, and not reload all local dependencies even when they are modified.

--------------------
to answer you questions:

> What command do you use to start ghcid? 

- either plain `ghcid` but nothing reload,
- either `ghcid -c "stack ghci toplevelpackage" ` but modifications done in other local dependencies of  toplevelpackage are not reloaded.

> Which directory are you starting ghcid from?

I always launch command from the root project folder.

> Can you do a ls -a on that? 

(slightly edited)

```shell
toplevelpackage $ ls -la
total 96
drwxr-xr-x   24 rvion  staff   816 Apr 12 18:01 .
drwxr-xr-x  147 rvion  staff  4998 Apr 12 18:03 ..
-rw-r--r--@   1 rvion  staff  8196 Apr 11 14:14 .DS_Store
drwxr-xr-x   16 rvion  staff   544 Apr 12 18:34 .git
-rw-r--r--    1 rvion  staff   212 Apr 11 14:05 .gitignore
-rw-r--r--    1 rvion  staff   237 Apr 11 16:04 .on-save.json
drwxr-xr-x    6 rvion  staff   204 Apr 11 13:31 .stack-work
-rwxr-xr-x@   1 rvion  staff  2810 Feb 29 08:16 .stylish-haskell.yaml
-rw-r--r--    1 rvion  staff   196 Apr 12 12:27 TopLevelPackage.hs
-rw-r--r--    1 rvion  staff  4823 Apr 11 16:02 README.md
drwxr-xr-x    9 rvion  staff   306 Apr 11 16:02 app
drwxr-xr-x    6 rvion  staff   204 Apr  6 17:09 arch
drwxr-xr-x    9 rvion  staff   306 Mar 19 11:09 auth
drwxr-xr-x   13 rvion  staff   442 Apr  7 09:49 client
-rw-r--r--    1 rvion  staff  1086 Apr 12 09:27 toplevelpackage.cabal
-rw-r--r--    1 rvion  staff   632 Apr 12 09:27 toplevelpackage.hpack.yaml
drwxr-xr-x    3 rvion  staff   102 Apr 11 12:23 doc
drwxr-xr-x    6 rvion  staff   204 Apr 11 14:06 org
drwxr-xr-x   11 rvion  staff   374 Apr 12 13:03 orm
drwxr-xr-x    8 rvion  staff   272 Apr 11 15:38 pghs
drwxr-xr-x@   7 rvion  staff   238 Apr 11 12:25 scripts
drwxr-xr-x    5 rvion  staff   170 Apr 11 14:09 sql
-rw-r--r--    1 rvion  staff   968 Apr 11 16:14 stack.yaml
drwxr-xr-x    6 rvion  staff   204 Apr 11 16:03 types
```

> Is there a .ghci file or directory?

No

> why doesn't just plain vanilla ghcid work. It isn't loading anything to start with

as I wrote in ([my comment above](https://github.com/ndmitchell/ghcid/issues/57#issuecomment-208787546)) 

here is the output of a plain `ghcid` command invocation at the root of the folder:

```
$ ghcid
Loading stack ghci --test --ghci-options=-fno-code ...

* * * * * * * *
The main module to load is ambiguous. Candidates are:
1. Package `app' component exe:app-example with main-is file: /Users/rvion/dev/cogito/app/Main.hs
2. Package `pghs' component exe:pg2hs with main-is file: /Users/rvion/dev/cogito/pghs/Main.hs
You can specify which one to pick by:
Specify main module to use (press enter to load none): Not loading any main modules, as no valid module selected
 * Specifying targets to stack ghci e.g. stack ghci app:exe:app-example

 * Specifying what the main is e.g. stack ghci --main-is app:exe:app-example
 * Choosing from the candidate above [1..2]
* * * * * * * *

Configuring GHCi with the following packages: cogito, app, orm, pghs, types
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[ 1 of 40] Compiling PG.Types         ( /Users/rvion/dev/cogito/pghs/src/PG/Types.hs, nothing )
[ 2 of 40] Compiling PG.Dump          ( /Users/rvion/dev/cogito/pghs/src/PG/Dump.hs, nothing )
[ 3 of 40] Compiling Gen.Types        ( /Users/rvion/dev/cogito/pghs/src/Gen/Types.hs, nothing )
[ 4 of 40] Compiling Gen.Pluralize    ( /Users/rvion/dev/cogito/pghs/src/Gen/Pluralize.hs, nothing )
...


--------------

**Comment by rvion** [comment] 2016-04-13 10:21
@ndmitchell 

ok. I finally understood the problem (or at least a good part of it):

stack ghci has a `--load-local-deps` flag.
ghcid should use it by default I think.

this is working fine for me:
```shell
ghcid -c "stack ghci toplevelmodule --load-local-deps" --test="..."
```

now, the last thing to figure out is why the default plain `ghcid` command (without args) doesnt' reload anything. 
(is is also just the --load-local-deps flag missing ? If so, problem fixed. I think there might be something more to it, because `ghcid -c "stack ghci --load-local-deps" --test="2+2"` load everything at startup, but never reload anything, and never refresh the screen neither)

**Comment by ndmitchell** [comment] 2016-04-14 19:14
Thanks for the analysis. I'm afraid I didn't get time to look at it in detail yet, and probably won't until next week - but do hope to take a look pretty soon.

**Comment by rvion** [comment] 2016-04-14 19:36
Thanks :)
All of your tools are great gift to the community

**Comment by ndmitchell** [comment] 2016-04-18 20:16
Thanks for the test case. The issue is that Stack drops us out at:

    Specify main module to use (press enter to load none):

Ghcid then sends some essential configuration commands to GHCi to allow it to detect loading has finished. They get sent to that prompt, and thus do nothing. As a result, ghcid can't tell that loading finished. I tried sending an extra `\n` before my important commands, but Stack seemingly doesn't accept input that has already arrived - maybe that's a stack bug. Needs more investigation.

**Comment by ndmitchell** [comment] 2016-04-18 20:27
Hmm, it actually seems that Stack is swallowing subsequent commands. If I create a file `input.txt`:

    1
    print 1

And run:

    type input.txt | stack ghci --test

Then the line `1` goes to stack to select the right project, but the `print 1` line gets swallowed. Maybe a changing in buffering can get Stack to only consume 1 line? Otherwise some flag to say don't read it from the terminal might be a good idea.

**Comment by mgsloan** [comment] 2016-04-18 20:27
It's probably because we're passing over control of stdout / stdin to the ghci project, but that doesn't pass along the buffered input.  Just a guess!

**Comment by ndmitchell** [comment] 2016-04-18 20:29
@mgsloan, that was my guess too - I wondered if setting LineBuffering/NoBuffering explicitly on stdin might help. I do that on my side, but it would need to be present in the Stack side too - and even then might make no difference if the buffering happens somewhere you can't see it.

**Comment by mgsloan** [comment] 2016-04-18 20:48
I tried `NoBuffering` in stack, but no such luck with `printf "1\nputStrLn 2" | stack ghci` with multiple executable targets.  Not sure what's up with that.

One approach might be to pass in `--ghci-options="--ghci-script ..."` or something like that.

**Comment by ndmitchell** [comment] 2016-04-19 08:49
I tried no buffering in a small sample program, in both Haskell and C, and in neither case could I get the child process to pick up stdin. It just seems to be "not possible" as far as I can tell.

For `ghcid`, I regularly need to send stuff on stdin, and get stuff on stdout. I could use `ghci-script` to send the setup commands, watch for them to echo back, and then send real commands to stdin. There are a few issues:

# What if the parent process is still pulling off stdin? I don't think this happens, but it seems that I'm not getting guaranteed behaviour anymore.
# Given an arbitrary command it can be hard to add in a ghci-script, since I don't know if I send it directly, through stack, or something else.
# I believe ghci script can conflict with `.ghci` files, which would be a pain.

So an easier alternative would be to ask Stack to not put that, and pick the default. Is that an option @mgsloan?

**Comment by mgsloan** [comment] 2016-04-19 23:22
> Given an arbitrary command it can be hard to add in a ghci-script, since I don't know if I send it directly, through stack, or something else. 

True, it may be necessary to make ghcid know about stack.  I realize that's counter the minimalist design, but hey, if we want the functionality

> I believe ghci script can conflict with .ghci files, which would be a pain.

I believe it's possible to generate ghci scripts that tend to play well with others - see https://github.com/commercialhaskell/stack/issues/1888

**Comment by luigy** [comment] 2016-04-20 01:06
> I tried NoBuffering in stack, but no such luck with printf "1\nputStrLn 2" | stack ghci with multiple executable targets. Not sure what's up with that.
It would be nice for this to work!
>So an easier alternative would be to ask Stack to not put that, and pick the default

**Comment by mgsloan** [comment] 2016-04-21 20:48
I had a thought for how to solve this.  What if `ghcid` left stdin to the user until it sees a line of output matching `GHCi, version ...`?

**Comment by ndmitchell** [comment] 2016-04-21 20:54
Yep, that might work - will give it a whirl.

**Comment by ndmitchell** [comment] 2016-04-25 09:43
I followed @mgsloan's suggestion, and it worked. With that, I can load up the project properly. I am not using `--load-local-dep`, but it doesn't seem to be necessary.

I'm still gently unwary with waiting for the `GHCi, version` string to go past, but let's address that if it turns out to be problematic somewhere.

**Comment by ndmitchell** [comment] 2016-04-25 10:56
This doesn't work because:

* I have to send `\n` to the stdin before doing anything else, so that I can get past the interactive prompt Stack puts up.
* I don't know in advance if Stack is going to ask me a question, and if it doesn't, ghci gets the `\n` and then the prompt hasn't been changed so that goes wrong.

Now trying to only send `\n` if I see a stack specific prefix, but that's getting very ugly. Having an option to Stack to not read this preference from stdin, some kind of `--main-is whatever_the_default` would make it cleaner.

**Comment by ndmitchell** [comment] 2016-04-25 11:07
I implemented something which looks for a Stack line and send the `\n` then. Seems to work, but yuk. @mgsloan - would you guys be happy with a flag to say "use the default, don't ask me"?

**Comment by ndmitchell** [comment] 2016-04-25 13:25
OK, I've implemented more hacks, and I think it's now working. It is quite unpleasant, and I worry about the long-term robustness.

**Comment by mgsloan** [comment] 2016-04-25 21:12
Cool!  Yeah, not super pleasant I realize.  Thanks for making it happen!

We could also add a flag, certainly.

**Comment by ndmitchell** [comment] 2016-04-26 08:21
I've put all the stack requests into https://github.com/commercialhaskell/stack/issues/1948#issuecomment-213109908 so closing this.

**Closed by ndmitchell** 2016-04-26 08:21 UTC
