### ISSUE TITLE
No support for color output

### ISSUE THREAD

**Issue by scarvalhojr** [ndmitchell/ghcid#144] opened 2018-03-16 18:16 UTC
When using GHCI with colored output (`-fdiagnostics-color=always`), the syntax highlighted code isn't showed by `ghcid`. As example, running without colors, I can see the following warning (in black and white) in one source file:
```
bigsorting.hs:11:20: error:
    • Variable not in scope: line :: String
    • Perhaps you meant one of these:
        ‘line1’ (line 10), ‘lines’ (imported from Prelude)
   |
11 |   let count = read line :: Int
   |                    ^^^^
```

Forcing `ghci` to use colors with `-fdiagnostics-color=always` causes `ghcid` to display the following (note the missing last 3 lines):
```
bigsorting.hs:11:20: error:
    • Variable not in scope: line :: String
    • Perhaps you meant one of these:
        ‘line1’ (line 10), ‘lines’ (imported from Prelude)
```

This is affecting `ghcid` version v0.6.10 with GHCi 8.2.1 on a Mac OS 10.12.6. I tested and confirmed this behavior on both the native Mac Terminal app as well as on iTerm2.

**Comment by vaibhavsagar** [comment] 2018-03-19 15:04
This is a duplicate of #87.

**Comment by ndmitchell** [comment] 2018-04-07 21:53
Thanks @vaibhavsagar - very similar to #87, but this one is a different entry point into the problem - and one I'm inclined to tackle first.

**Comment by ndmitchell** [comment] 2018-04-08 20:36
@scarvalhojr - enough has changed that I'm going to assume this bug went away in the rewrites. If not, please test with HEAD (or after a release) and reopen. On the plus side, you now get colors.

**Closed by ndmitchell** 2018-04-08 20:36 UTC

**Comment by scarvalhojr** [comment] 2018-04-09 11:04
Yes, I tested it with HEAD and it works like a treat. Thanks @ndmitchell
