### ISSUE TITLE
GHCID is failing when there is no src directory in the project root dir

### ISSUE THREAD

**Issue by mageshb** [ndmitchell/ghcid#120] opened 2017-12-20 08:49 UTC
I have a repo with following structure
```
proj
|_sub-proj1
    |_src
    |_ sub-proj1.cabal
|_sub-proj2
    |_src
    |_ sub-proj1.cabal
|_cabal.project
```

And I'm trying to run ghcid with
```
ghcid --height=8 --topmost --reload=sub-proj1/src --reload=sub-proj2/src --command='cabal --project-file=cabal.project --builddir=dist-ghc new-repl all' --warning
```

With above cmd, I'm getting following error
```
Reloading...
  /home/magesh/sub-proj1/src/: can't watch what isn't there!: does not exist
```
But when I create a folder called ***src*** and move ***sub-proj1*** and ***sub-proj2*** into it, things are working as expected.

Is this a bug or am I missing something?

**Comment by ndmitchell** [comment] 2017-12-20 09:38
Which working directory are running from. Why are you passing the reload flag? Ghcid usually figures that out itself. If you remove the reload flags does it work?

**Comment by mageshb** [comment] 2017-12-20 09:46
I'm running from directory where cabal.project file is there (***proj***).
In the first case (when src is not there at root), I'm getting the same error without the reload
In the second case (when I have src dir at root), It is not picking up the file changes without reload

**Comment by ndmitchell** [comment] 2018-01-22 21:38
I'm confused - something isn't adding up. Have you got any demo code with which I can reproduce this issue? I don't think you should need `--reload` at all (that's what GHC figures out for you), and if you did put it, it should work fine given the directory. That said, I suspect whatever is stopping one from working is also stopping the other from working...

**Comment by srid** [comment] 2018-03-10 17:44
@ndmitchell You can reproduce this issue using https://github.com/ElvishJerricco/reflex-project-skeleton

```
git submodule update --init --recursive
./cabal new-repl backend # run once, and exit, for caching builds
ghcid -c './cabal new-repl backend'
```
(Note that the `./cabal` script is simply a nix wrapper to get cabal to use the proper environment).

**Comment by srid** [comment] 2018-03-10 17:45
A workaround is to run `(cd backend && ghcid -c '../cabal new-repl backend')` but it won't rebuild if `./common` package (which `backend` depends on) changes.

**Comment by srid** [comment] 2018-03-10 17:49
Judging from the verbose logs (see below) I think what is happening is that ghcid asks ghci for modules loaded, and ghci returns the paths **relative** to the cabal project directory (which is a sub directory, not a root directory, in reflex-project-skeleton) - but ghcid treats them as relative to the root project directory and thus fails.

```
%STDIN: :reload
%STDIN: INTERNAL_GHCID.putStrLn "#~GHCID-FINISH-7~#"
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr "#~GHCID-FINISH-7~#"
%STDOUT: #~GHCID-START~##~GHCID-START~#Ok, modules loaded: Main.
%STDOUT: #~GHCID-START~##~GHCID-FINISH-7~#
%STDERR: #~GHCID-FINISH-7~#
%STDIN: :show modules
%STDIN: INTERNAL_GHCID.putStrLn "#~GHCID-FINISH-8~#"
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr "#~GHCID-FINISH-8~#"
%STDOUT: #~GHCID-START~##~GHCID-START~#Main             ( src/Main.hs, interpreted )
%STDOUT: #~GHCID-START~##~GHCID-FINISH-8~#
%STDERR: #~GHCID-FINISH-8~#
%MESSAGES: []
%LOADED: ["src/Main.hs"]

All good (1 module, at 12:47:25)

%WAITING: src/Main.hs

Reloading...
  Error when waiting, if this happens repeatedly, raise a ghcid bug.
  /home/srid/code/Taut/src/: can't watch what isn't there!: does not exist
```

**Comment by ndmitchell** [comment] 2018-04-08 21:59
Thanks for the analysis @srid - much appreciated (I'm on Windows, so it doesn't sound like I'd be able to reproduce with Nix scripts etc even if I wanted to). To clarify, so I can reproduce in an isolated form locally, you do:

    ghcid -c './cabal new-repl backend'

And the `./cabal` as part of its magic does a `cd backend`, and thus all paths are relative to the wrong thing?

I think this can be fixed by doing `:show paths` in `ghci` and qualifying all the paths before I use them to do waiting on.

**Comment by ndmitchell** [comment] 2018-04-11 21:39
I can't test your example because I'm on Windows, but I believe I've now fixed this in ghcid HEAD. I also added a test, which I confirm didn't work before, which makes me gently optimistic I fixed it.

**Comment by ndmitchell** [comment] 2018-04-11 21:44
Tentatively marking as closed, but please reopen if you can reproduce it with the latest HEAD of ghcid, or the next release.

**Closed by ndmitchell** 2018-04-11 21:44 UTC
